### ISSUE TITLE
Database field input tips that support CDS

### ISSUE THREAD

**Issue by revolveyao** [marcellourbani/vscode_abap_remote_fs#96]
Writing CDS is the most commonly used feature, hoping to include field tips

**Comment by marcellourbani** [comment]
I agree. had a quick look months ago, and unlike regular ABAP is mostly done by eclipse, so it requires a significant amount of work.

Also recently I slowed down this project due to other commitments. I do plan to add new features, and more importantly to refactor the existing code which is quite buggy and a bit messy. But will definitely pick this up at some point

**Comment by revolveyao** [comment]
Your project is great. Hopefully I can also learn ts and then join the development.

**Comment by marcellourbani** [comment]
Thank you!

**Comment by marcellourbani** [comment]
@revolveyao 
Last update should have got this working for the most part
No annotation or syntax completion for now
